[package]
name = "ptkcore"
version.workspace = true
edition.workspace = true
repository.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
serde.workspace = true
serde_yaml_ng.workspace = true
rust_decimal.workspace = true
glam.workspace = true
thiserror.workspace = true
rand.workspace = true
